### PR TITLE
rest resource updates

### PR DESCRIPTION
**Pull request by RutvikS-crest**
- Made payload optional, it is required only if method is POST or PUT.
-  support for ndfc type urls.

### CODE REVIEW

**Comment by qsnyder** [comment]
This is the case for a sync and deploy action. Up to this point I've just used an empty set as the payload, but the docs weren't clear on this.
Removing that would make it much nicer.

**Comment by RutvikS-crest** [comment]
Hi @dsx1123, I have made the payload optional, without any validations, please test it from your end.

**Review by lhercot — APPROVED** [review]
LGTM

**Review by lhercot — APPROVED** [review]
LGTM

**Pull request merged**
