### PR TITLE
Issue 63/61

### PR DESCRIPTION
**Pull request by RutvikS-crest**

### CODE REVIEW

**Comment by dsx1123** [comment]
the fixed partially works on NDFC, here is a scenario that is not working:
1. first create the network without any attachment, the `deploy` has to be set to false:
```tf
resource "dcnm_network" "networks" {
  fabric_name  = "MSD"
  name         = "MSD_test"
  network_id   = "31000"
  vlan_id      = "1000"
  vlan_name    = "MSD_test"
  description  = "create from terraform"
  vrf_name     = "BLUE-TF"
  ipv4_gateway = "1.1.1.1/24"

  deploy = false
}
```
2. then later on, it need be attached to new switches, modify the plan like this:
```tf
resource "dcnm_network" "networks" {
  fabric_name  = "MSD"
  name         = "MSD_test"
  network_id   = "31000"
  vlan_id      = "1000"
  vlan_name    = "MSD_test"
  description  = "create from terraform"
  vrf_name     = "BLUE-TF"
  ipv4_gateway = "1.1.1.1/24"

  deploy = true
  attachments {
    serial_number = data.dcnm_inventory.fabric1_leaf1.serial_number
    attach        = true
    switch_ports  = ["Ethernet1/1"]
  }
  attachments {
    serial_number = data.dcnm_inventory.fabric2_leaf1.serial_number
    attach        = true
    switch_ports  = ["Ethernet1/1"]
  }
}
```

Failed with error:

```
dcnm_network.networks: Modifying... [id=MSD_test]
╷
│ Error: 400 Error : "Invalid Mulicast Group Addressnull"
│
│   with dcnm_network.networks,
│   on main.tf line 33, in resource "dcnm_network" "networks":
│   33: resource "dcnm_network" "networks" {
```

**Comment by RutvikS-crest** [comment]
Hi @dsx1123,
I have pushed a fix, it should handle this case. Let me know if you notice anything else.

**Comment by dsx1123** [comment]
Issue #61  is not fixed in this PR:
```hcl
terraform {
  required_providers {
    dcnm = {
      source  = "cisco/com/dcnm"
      version = "0.0.1"
    }
  }
}

provider "dcnm" {
  # Cisco DCNM/NDFC user name
  username = "admin"
  # Cisco DCNM/NDFC password
  password = "ins3965!"
  # Cisco DCNM/NDFC url
  url      = "https://172.25.74.53"
  insecure = true
  # Used to select DCNM or NDFC for authentication purposes
  platform = "dcnm"
}

data "dcnm_inventory" "leaf1" {
  fabric_name = "fabric_IR"
  switch_name = "leaf1"
}

resource "dcnm_network" "overlay_network" {
  fabric_name = "fabric_IR"
  name        = "Devnet"
  network_id  = 30001
  vrf_name    = "devnet"
  deploy      = true
  attachments {
    serial_number = data.dcnm_inventory.leaf1.serial_number
    attach        = true
  }
}
```
above is the example of tf config. the fabric fabric_IR has ingress repelication set to BUM.

**Review by lhercot — DISMISSED** [review]
LGTM

**Review by lhercot — APPROVED** [review]
LGTM

**Pull request merged**
